import { Procedure } from "../../types/PatientTypes";

export const PROCEDURES: Procedure[] = [
  {
    id: 1,
    name: "Examination",
    description: null,
    defaultPrice: 200,
    isActive: 1,
  },
  {
    id: 2,
    name: "Simple Filling",
    description: null,
    defaultPrice: 1500,
    isActive: 1,
  },
  { id: 3, name: "RCT", description: null, defaultPrice: 2000, isActive: 1 },
  {
    id: 4,
    name: "Zirconium Crown",
    description: null,
    defaultPrice: 100,
    isActive: 1,
  },
  {
    id: 5,
    name: "PMF Crown",
    description: null,
    defaultPrice: 2000,
    isActive: 1,
  },
  {
    id: 6,
    name: "Metal Crown",
    description: null,
    defaultPrice: 1500,
    isActive: 1,
  },
  {
    id: 7,
    name: "Veneer Direct",
    description: null,
    defaultPrice: 2000,
    isActive: 1,
  },
  {
    id: 8,
    name: "Extraction (Simple)",
    description: null,
    defaultPrice: 500,
    isActive: 1,
  },
  {
    id: 9,
    name: "Extraction (Complex)",
    description: null,
    defaultPrice: 1500,
    isActive: 1,
  },
  {
    id: 10,
    name: "Extraction (Surgical)",
    description: null,
    defaultPrice: 3000,
    isActive: 1,
  },
  {
    id: 11,
    name: "Mucocele Removing",
    description: null,
    defaultPrice: 5000,
    isActive: 1,
  },
  {
    id: 12,
    name: "Crown Lengthening",
    description: null,
    defaultPrice: 1500,
    isActive: 1,
  },
  {
    id: 13,
    name: "RCT + Post Corel + Crown",
    description: null,
    defaultPrice: 5000,
    isActive: 1,
  },
  {
    id: 14,
    name: "Dentures Upper Lower",
    description: null,
    defaultPrice: 30000,
    isActive: 1,
  },
  {
    id: 15,
    name: "Orthodontics (Basic)",
    description: null,
    defaultPrice: 300,
    isActive: 1,
  },
  {
    id: 16,
    name: "Orthodontics (Standard)",
    description: null,
    defaultPrice: 400,
    isActive: 1,
  },
  {
    id: 17,
    name: "Orthodontics Visit",
    description: null,
    defaultPrice: 1500,
    isActive: 1,
  },
  {
    id: 18,
    name: "Implant Surgery Only (Standard)",
    description: null,
    defaultPrice: 400,
    isActive: 1,
  },
  {
    id: 19,
    name: "Implant Surgery Only (Premium)",
    description: null,
    defaultPrice: 500,
    isActive: 1,
  },
  {
    id: 20,
    name: "Scaling & Polishing",
    description: null,
    defaultPrice: 1500,
    isActive: 1,
  },
  {
    id: 21,
    name: "Bleaching",
    description: null,
    defaultPrice: 100,
    isActive: 1,
  },
  {
    id: 22,
    name: "Old Crown Cementation Fee",
    description: null,
    defaultPrice: 150,
    isActive: 1,
  },
];
