export const PROCEDURES = [
  { name: "Examination", price: 200 },
  { name: "Simple Filling", price: 1500 },
  { name: "RCT", price: 2000 },
  { name: "Zirconium Crown", price: 100 },
  { name: "PMF Crown", price: 2000 },
  { name: "Metal Crown", price: 1500 },
  { name: "Veneer Direct", price: 2000 },
  { name: "Extraction (Simple)", price: 500 },
  { name: "Extraction (Complex)", price: 1500 },
  { name: "Extraction (Surgical)", price: 3000 },
  { name: "Mucocele Removing", price: 5000 },
  { name: "Crown Lengthening", price: 1500 },
  { name: "RCT + Post Corel + Crown", price: 5000 },
  { name: "Dentures Upper Lower", price: 30000 },
  { name: "Orthodontics (Basic)", price: 300 },
  { name: "Orthodontics (Standard)", price: 400 },
  { name: "Orthodontics Visit", price: 1500 },
  { name: "Implant Surgery Only (Standard)", price: 400 },
  { name: "Implant Surgery Only (Premium)", price: 500 },
  { name: "Scaling & Polishing", price: 1500 },
  { name: "Bleaching", price: 100 },
  { name: "Old Crown Cementation Fee", price: 150 },
];